import type { Badge, Memory, Place, SpecialDate, Suggestion } from "@/types";

export const MOCK_BADGES: Badge[] = [
  {
    id: "first_log",
    name: "Primeira Memória",
    description: "Registrou o primeiro dia do ciclo",
    icon: "star",
    earned: true,
    earnedDate: "2025-04-01",
    xp: 50,
  },
  {
    id: "week_streak",
    name: "7 Dias Juntos",
    description: "Registrou 7 dias seguidos",
    icon: "flame",
    earned: true,
    earnedDate: "2025-04-07",
    xp: 100,
  },
  {
    id: "partner_connected",
    name: "Almas Conectadas",
    description: "Conectou com seu parceiro",
    icon: "heart",
    earned: true,
    earnedDate: "2025-03-15",
    xp: 150,
  },
  {
    id: "empathy_master",
    name: "Mestre da Empatia",
    description: "Compartilhou humor por 30 dias",
    icon: "award",
    earned: false,
    xp: 200,
  },
  {
    id: "memory_keeper",
    name: "Guardião de Memórias",
    description: "Criou 10 memórias especiais",
    icon: "camera",
    earned: false,
    xp: 150,
  },
  {
    id: "cycle_expert",
    name: "Expert do Ciclo",
    description: "Acompanhou 3 ciclos completos",
    icon: "moon",
    earned: false,
    xp: 300,
  },
];

export const MOCK_MEMORIES: Memory[] = [
  {
    id: "1",
    date: "2025-04-20",
    title: "Primeiro piquenique",
    description: "Um dia lindo no parque, com sol e muita risada.",
    type: "milestone",
    isFavorite: true,
  },
  {
    id: "2",
    date: "2025-03-14",
    title: "Aniversário de 1 ano",
    description: "Jantar especial e passeio pela cidade à noite.",
    type: "anniversary",
    isFavorite: true,
  },
  {
    id: "3",
    date: "2025-02-14",
    title: "Dia dos Namorados",
    description: "Surpresa incrível com flores e cartas escritas à mão.",
    type: "milestone",
    isFavorite: false,
  },
  {
    id: "4",
    date: "2025-01-01",
    title: "Réveillon juntos",
    description: "Virada do ano com fogos e muita alegria.",
    type: "note",
    isFavorite: false,
  },
];

export const MOCK_SPECIAL_DATES: SpecialDate[] = [
  {
    id: "1",
    name: "Aniversário do casal",
    date: "2025-03-14",
    type: "anniversary",
    icon: "heart",
    notes: "1 ano juntos",
  },
  {
    id: "2",
    name: "Aniversário dela",
    date: "2025-07-22",
    type: "birthday",
    icon: "gift",
  },
  {
    id: "3",
    name: "Primeiro encontro",
    date: "2025-02-10",
    type: "firstDate",
    icon: "coffee",
  },
  {
    id: "4",
    name: "Viagem para o litoral",
    date: "2025-06-15",
    type: "trip",
    icon: "map-pin",
  },
];

export const MOCK_PLACES: Place[] = [
  {
    id: "1",
    name: "Café dos Sonhos",
    type: "cafe",
    description: "Café aconchegante com ambiente intimista e chá especial.",
    distance: "0.8 km",
    rating: 4.8,
    tags: ["Aconchegante", "Quieto", "Chá", "Bolo"],
    phase: ["menstrual", "pms", "luteal"],
  },
  {
    id: "2",
    name: "Restaurante Luna",
    type: "restaurant",
    description: "Jantar romântico com culinária italiana e vinho selecionado.",
    distance: "1.2 km",
    rating: 4.9,
    tags: ["Romântico", "Italiano", "Vinho", "Candlelight"],
    phase: ["ovulation", "follicular"],
  },
  {
    id: "3",
    name: "Parque das Flores",
    type: "park",
    description: "Parque florido perfeito para caminhadas a dois.",
    distance: "2.1 km",
    rating: 4.7,
    tags: ["Ao ar livre", "Natureza", "Caminhada", "Flores"],
    phase: ["follicular", "ovulation"],
  },
  {
    id: "4",
    name: "Spa Serenity",
    type: "spa",
    description: "Spa de luxo com massagens para casais e aromaterapia.",
    distance: "3.0 km",
    rating: 4.9,
    tags: ["Relaxante", "Massagem", "Casal", "Luxo"],
    phase: ["menstrual", "pms", "luteal"],
  },
  {
    id: "5",
    name: "Cinema Arte",
    type: "cinema",
    description: "Cinema alternativo com filmes premiados e assentos confortáveis.",
    distance: "1.5 km",
    rating: 4.6,
    tags: ["Cinema", "Arte", "Pipoca", "Confortável"],
    phase: ["luteal", "pms", "menstrual"],
  },
  {
    id: "6",
    name: "Rooftop Bar Vista",
    type: "bar",
    description: "Bar no terraço com vista panorâmica e drinks artesanais.",
    distance: "2.5 km",
    rating: 4.7,
    tags: ["Vista", "Drinks", "Pôr do sol", "Animado"],
    phase: ["ovulation", "follicular"],
  },
];

export const MOCK_SUGGESTIONS: Suggestion[] = [
  {
    id: "1",
    title: "Banho de ervas relaxante",
    description: "Um banho com lavanda e sal marinho para aliviar as cólicas.",
    category: "care",
    icon: "droplets",
    phase: "menstrual",
  },
  {
    id: "2",
    title: "Jantar romântico em casa",
    description: "Prepare uma refeição especial com velas e música suave.",
    category: "activity",
    icon: "heart",
    phase: "menstrual",
  },
  {
    id: "3",
    title: "Trilha ao amanhecer",
    description: "Energia em alta! Perfeita para aventuras ao ar livre.",
    category: "activity",
    icon: "map-pin",
    phase: "follicular",
  },
  {
    id: "4",
    title: "Sessão de fotos",
    description: "Momento ideal para criar memórias visuais incríveis.",
    category: "activity",
    icon: "camera",
    phase: "ovulation",
  },
  {
    id: "5",
    title: "Noite de filmes",
    description: "Escolha um filme leve e curta com chocolate quente.",
    category: "movie",
    icon: "film",
    phase: "pms",
  },
  {
    id: "6",
    title: "Massagem nos pés",
    description: "Um gesto simples de muito carinho e cuidado.",
    category: "care",
    icon: "heart",
    phase: "pms",
  },
];
